#!/bin/bash
set -e

echo "🚀 Deploying Video Downloader Backend to Render..."
echo ""
echo "Instructions to deploy via Render:"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Select 'Deploy existing GitHub repo' or 'Public Git repository'"
echo "4. Enter this repo: https://github.com/dadasdawqwe/download (or your fork)"
echo "5. Fill in:"
echo "   - Name: video-downloader-backend"
echo "   - Runtime: Python 3.11"
echo "   - Build Command: pip install -r backend/requirements.txt"
echo "   - Start Command: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "   - Plan: Free"
echo "6. Click 'Deploy'"
echo ""
echo "Your backend URL will be: https://video-downloader-backend.onrender.com"
echo ""
echo "After deployment, update your frontend:"
echo "  - Update VITE_API_URL in netlify.toml"
echo "  - Update window.__API_URL__ in frontend/env.js"
echo "  - Redeploy to Netlify"
